### ISSUE TITLE
jquery-mobile-iscrollview 1.3.1 scrolls header and footer

### ISSUE THREAD

**Issue by play75010** [watusi/jquery-mobile-iscrollview#102]
Hello.

Just installed the 1.3.1 with JQ2.0 & JQM1.3.1 and Phonegap 2.6.

Both headers and footers scroll with the new version when released as an app.

**Comment by jtara** [comment]
Please drop-back to jQuery 1.9.1, since jQuery Mobile 1.3.1 is not yet compatible with jQuery 2.0.

If that doesn't work, I will need more details. (For example, iOS or Android? Need to see JS links in `<head>`, etc.)

"headers and footers scroll" sounds like the widget simply is not being initialized, and you are just seeing a normal page scroll. Did you check to make sure that all libraries are in the correct order and are, in fact, being loaded? Did you check with Web Inspector or Weinre to see if the widget was initialized?

**Comment by play75010** [comment]
You're right, it sounds like it's not initialized. Certainly a mistake in the naming of the 2 different versions of the JS.

I'm pretty sure it's the case and I'm sorry for issuing a problem. I'll check tomorrow at work.

I've been using JQ2.0 since the beginning. I'll check if 1.9.1 brings any change. 

Thanks for the answer and sorry again if I it's a typo in my code.
