### ISSUE TITLE
iscrollview inside of an external jqm panel

### ISSUE THREAD

**Issue by MaximSpirin** [watusi/jquery-mobile-iscrollview#152]
Hello,
did anybody implement iscrollview inside of a jqm panel(preferably external ie not nested in a page)?
As I see data-iscroll attribute doesnt force browser to create an instance of iscrollview and the document structure remains the same as I have defined i.e. it doesnt add all auxiliary items/classes like iscroll-wrapper..etc. As the panel is an external one I am creating that it manually as by calling:

``` javascript
$(panelElement).panel();
$(panelElement).trigger("create");
```

And then call `$(panelElement).trigger("updateLayout");` after each DOM manipulation
jqm version is 1.4.3 and iscrollview is the last stable version.

Any advice will be highly appreciated.

Thanks,
Max

**Comment by frankie-loves-jesus** [comment]
From what I gather iScrollView is obsolete. Personally I replaced jQM's native panel with Snap.js (at least until jQM's native panel becomes scrollable in version 1.7):
- https://github.com/watusi/jquery-mobile-iscrollview/issues/118#issuecomment-48835419
- http://stackoverflow.com/questions/26288666/add-destroy-method-to-snap-js-mobile-panel-plugin

Hope it helps.

**Comment by jtara** [comment]
I use it to scroll inside of popups. I've never tried a panel, and I don't think it would be easy, because the panel code itself assumes it is the height of the entire document. The panel code would need to be re-written.

I do something similar to a panel, but it does not open and close. It is just a scrollable sidebar that I use for some navigation (like the jQuery Mobile documentation "quick index"). I show the sidebar when the screen is landscape, and hide it when it is portrait. There I do use iscrollview to scroll within the navigation sidebar and the main content separately.
