### ISSUE TITLE
Is jquery.actual.js reliable?

### ISSUE THREAD

**Issue by putztzu** [watusi/jquery-mobile-iscrollview#16]
Am running into a possible issue where the page initially does not load properly... Am seeing a variety of ways the page does not load properly like truncated objects, missing objects.

Believe that when I see objects rendered abnormally large then objects may be rendered off-screen.

A page refresh addresses the problem, but would be a poor workaround only when the User knows the page isn't rendered properly. A new User or someone who doesn't know what to expect on the page would not know that anything was amiss.

Testing on Android 2.3.4.

TS

**Comment by jtara** [comment]
What happens if you set the refreshOnPageBeforeShow option to true? 

As well, what happens if you increase the refreshDelay option value? It defaults to 200mSec for Android. It may have to be increased on some devices. Unfortunately, there is too much fragmentation in the Android market to come up with a universal value for this.

Is the incorrect rendering permanent, or does it briefly appear wrong and then corrects itself?

Unfortunately, the latter is normal jQuery Mobile behavior when loading the first page. It's due to JQM's progressive enhancement. This isn't seen on page transitions, because the page is constructed prior to the transition.

Can you upload an example screen capture?

**Comment by putztzu** [comment]
Hello,
Before trying this setting i reviewed your documentation.

Isn't efreshOnPageBeforeShow supposed to already default to true if I'm using your version of iscroll?

I'll try modifying the refreshDelay option, but I'll need to think how this setting might affect what I'm looking at.

The problem is "permanent" in that most of the time, the problem doesn't fix itself. By "most" I'm not absolutely sure that there might have been a momentary problem before auto-fixing a time or two... I wasn't looking for that so didn't really notice for sure.

TS

**Comment by jtara** [comment]
It's the opposite.

refreshOnBeforePageShow is true if using the unmodified iScroll, since it can't determine dimensions while the page is hidden.

If using the forked version, it defaults to false.

Does the problem occur on desktop, or only mobile? Desktop browsers should be fast enough that there shouldn't be an issue.

**Comment by jtara** [comment]
jquery.actual will no longer be used starting with 1.2. However, a similar technique is being used.

**Comment by jtara** [comment]
jquery.actual is no longer used by the widget.
