### ISSUE TITLE
Video starts Flickering when using data-iscroll

### ISSUE THREAD

**Issue by mohsinraza** [watusi/jquery-mobile-iscrollview#19]
before using jquery-mobile-iscrollview when i play a  video through html video tag it works very well, but after using jquery-mobile-iscrollview I am facing a strange behavior regarding the video on iphone/ipod. it is working well on ipad. the video starts flickring on each page after playing it first time. this is very bad thing for my project. i tried different things for this but all unsuccessful.

Please help me ragarding this issue as soon as possible.

**Comment by jtara** [comment]
Can you clarify where the video tag is placed? Is it in the scroller, or somewhere else? Can you provide an example? Thanks.

**Comment by mohsinraza** [comment]
it is in the scroller I am attaching the full page source here.

          

```
    <div data-role="page" data-theme="a" id="howitwork">

        <!-- top header for title-bar  -->
        <div data-role="header" class="header" >
            <a href="#" data-rel="back" class='ui-btn-left ui-btn-inner mybtn_left top_btn_settings' data-transition="flip"></a> <!-- Back Home Button for iPhone  -->
            <div data-role="navbar" style="text-align:center;">
                <h4>How it Works</h4>
            </div>

        </div>

        <!-- /top header for title-bar -->

        <!-- ListView contents -->
        <div data-role="content" data-iscroll >
            <div>

                <ul data-role="listview" data-inset="true"> 

                    <li data-role="fieldcontain">
                        <video src="http://supporttelecom.org/Support%20Telecom%20MAY%202009-15.mov"  width="260" height="130" data-transition="flip"> </video>
                    </li>
                </ul>


                <ul data-role="listview" class="content_list" data-inset="true">
                    <li><a href="http://supporttelecom.org/Support%20Telecom%20MAY%202009-15.mov" data-transition="flip" style="color:#000;"><img src="iphone2x/4_ic@2x.png" class="ui-li-icon"/><p>Promo Video</p></a></li>
                    <li><a href="#charitypartnerpage" data-transition="flip" style="color:#000;"><img src="iphone2x/3_ic@2x.png"  class="ui-li-icon"/><p>Benefits for your Charity</p></a></li>
                    <li><a href="#businesspartnerpage" data-transition="flip" style="color:#000;"><img src="iphone2x/3_ic@2x.png" class="ui-li-icon"/><p>Benefits for you</p></a></li>

                </ul>

                <p style="font-size:9px;">material also available at <a href="http://supporttelecom.org/howitworks.html" rel="external" target="_blank">supporttelecom.org/howitworks.html</a></p>
            </div>
        </div>
        <!-- /list view content -->


    </div>
    <!-- /How It Works Page -->  
```

**Comment by jtara** [comment]
Video inside a scroller isn't something I plan to support, as it doesn't seem a reasonable thing to do in a scroller. As well, there seem to be numerous hurdles to making this work, and I don't have the time or interest to do this myself.

However, I am open to pull requests if somebody wants to work-out the details.

As a work-around, I'd suggest you put thumbnails in the scroller, and link to a full page or popup when the user taps on the thumbnail. I think that would provide a better user experience anyway.

I couldn't get so far as seeing the "flickering" issue. I wasn't able to get anything but a black box with iScroll enabled.
(I made sure first I could play the sample video without iScroll.) I tried adding a z-Index to the video tag, but that did not help. I am able to play videos in a desktop browser.

 Can you supply whatever CSS you used to get the video to show?

I also couldn't select the video in order to use the controls. I tried adding the <video> tag to the list of tags that allow clicks through, but that didn't help.

I'm going to close this issue, but will re-open if others have some insight into solving the problems.
