### ISSUE TITLE
Opera Mobile

### ISSUE THREAD

**Issue by brandonhall** [watusi/jquery-mobile-iscrollview#30]
Hey Jon,

Have you done any testing on Opera Mobile? We're having some issues with it in our implementation and I didn't know if you had worked with it any.

Thanks,
Brandon

**Comment by brandonhall** [comment]
I was able to fix our issues by calling the refresh function twice. Example:

```
if(window.opera) {
    self._scroller.jqmData('iscrollview').refresh();
}
```

**Comment by jtara** [comment]
I do test on Opera desktop, but not mobile.

If calling `refresh()` twice solves the problem, try increasing the value of the `refreshDelay` option. It defaults to 200 (mSec) for Android, and 0 otherwise. This is the amount of time it waits before actually doing the refresh. 0 doesn't really mean immediate, since a 0 timeout will still cause the Javascript engine to yield and (on most browsers) allow all scheduled rendering to run.
