### ISSUE TITLE
Conflict with select menus

### ISSUE THREAD

**Issue by rnevet** [watusi/jquery-mobile-iscrollview#5]
http://jquerymobile.com/demos/1.0a4.1/docs/forms/forms-selects.html

 Some of the select menus the ui-header css class is in use, this creates errors when calculating resizeWrapper height this code:

$page.find(this.options.fixedHeightSelector).each(function() {  // Iterate over headers/footers
      barsHeight += $(this).actual("innerHeight");
      });

**Comment by jtara** [comment]
That's bizarre! Do you know in what specific cases a select menu would have a .ui-header CSS class? (That is, when it isn't actually itself a header?) Could you post a sample?

I could use data-role="header" to select headers. Or, I could simply require that users add the iscrollview-foreground class to all headers and footers. I'd prefer not to do the latter, since I want it to be more automatic than that.

However, that would be an effective work-around until I'm able to reproduce and fix this bug. Set the fixedHeightSelector option to ".iscroll-foreground", or any other class you'd like to use to designate headers/footers, then use that class to mark your headers/footers. (default is ".ui-header, .ui-footer, .iscroll-foreground").

**Comment by jtara** [comment]
OK, it seems to be the native-looking picker that gets added on iOS (maybe others?) device. It's added as a header or footer, but is hidden until you actually use the select.

I think I can fix this easily by only including visible headers and footers.

**Comment by jtara** [comment]
Scratch that last comment. It isn't a native LOOKING picker. It IS a native picker. (on iOS). It is, essentially, a virtual keyboard.

I was seeing a bug related to scrolling an inset list. (new bug!). 

Still, it would be a good idea to omit any hidden header/footer in any case. If it's un-hidden, then the application needs to deal with it at that point.

I don't see anything with .ui-header or .ui-footer class that was created by the select widget. So, an example would still be very helpful.

**Comment by rnevet** [comment]
Hi,

In the link I posted if you look at the generated html in the custom example with the text "Standard: 7 day" you'll see this code:
`<div class="ui-selectmenu ui-overlay-shadow ui-corner-all pop ui-body-a in" style="top: 1240px; left: 521.5px; ">
<div class="ui-header ui-bar-c" style="display: none; "><h1 class="ui-title">`

Now I didn't manage to pinpoint exactly when this elements are causing this problem, we are using jquerymobile to change the pages and at some point this combination creates unwanted results. 
I used 'iscrollview-foreground' to mark the header and footer and removed the others from the code this did solve the issue.

**Comment by jtara** [comment]
The ui-selectmenu class is not present in selects starting with JQuery Mobile 1.0. It seems this was a bug in at least the A4 release and perhaps other pre-release versions of JQM.

JQuery Mobile >= 1.0 is a prerequisite for this widget.

I will keep a watch on this issue, and consider changing the selector for headers/footers to use the data-role attribute instead of the ui-header/ui-footer classes if I uncover cases where  ui-header is being used for something other than a page header.

In the mean time, the workaround, if you are using an alpha or beta version on JQM would be to make use of the fixedHeightSelector widget option.

**Comment by rnevet** [comment]
I think this issue also exists in jquerymobile 1.1.0, 
http://jquerymobile.com/demos/1.1.0/docs/forms/selects/custom.html look at the html created for the dialogs here.

As for my project, I'm using jquerymobile 1.0.1, I didn't notice the link I posted here was from an alpha version, the link was a mistake. I currently removed from your code the .ui-header,.ui-footer as a workaround and used ".iscroll-foreground" to mark the header and footer.

**Comment by jtara** [comment]
I've changed the default for fixedHeightSelector to use data-role to identify headers and footers. You are correct that select menus use .ui-header.

**Comment by jtara** [comment]
Reopened to close showing bug fixed...
