### ISSUE TITLE
jqmData("iscrollview") always null in jQm 1.3.0

### ISSUE THREAD

**Issue by vineey** [watusi/jquery-mobile-iscrollview#76]
using jQm 1.2.0 is working fine, but when i tried to switch to jQm 1.3.0, encountering this issue with jqmData("iscrollview"), it is always returning null, already upgraded from 1.2.5 to 1.2.6 of this plugin, issue still persist. I think it has to update to work with jQm1.3.0 regarding this matter.

**Comment by ghost** [comment]
This is indeed a bit broken due to changes made in jQuery and jQuery Mobile. But there is a (bit off a) workaround:

With this code I managed to get a simmiliar result with the old jqmData( "iscrollview" )

``` javascript
iscroll_view_obj = $( 'iscroll_view_target' ).iscrollview();
if( iscroll_view_obj[0] != undefined )
scrollObject = $( iscroll_view_obj[0] ).data( "mobileIscrollview" );
```

It doesnt really feel like a good sollution, but it works for me for now.

**Comment by jtara** [comment]
I don't understand what `iscroll_view_target` and `mobileIscrollview` are in the above. There seems to be something missing. Are these classes in your HTML?

**Comment by jtara** [comment]
Confirmed.

I'll update the documentation. Nothing I can do about this in the widget, since the way JQM uses the Widget Factory has changed.

I think you meant:

`iscroll_view_obj = $( '.iscroll_view_target' ).iscrollview();`

above, where `.iscroll_view_target` is the class of your wrapper element.

If you want to write application code that will work with either JQM 1.3 or <1.3, you could do this:

``` javascript
$scrollElement = $(iscroll_view_obj[0]);
scrollObject = $scrollElement.data("mobileIscrollview") || $scrollElement.jqmData("iscrollview");
```

Note that jqmData doesn't work to retrieve this with JQM 1.3. So, it is a change both in the naming convention and in the method used to access.

**Comment by ghost** [comment]
With 'iscroll_view_target' I ment the element where the iscroll_view plugin was created on. So yeah that could be a class or an id or anything.

(Sorry for the kinda slow response, not getting this in my email for some reason :) )
