### ISSUE TITLE
Header/footer in popups erroneously makes wrapper too short

### ISSUE THREAD

**Issue by jtara** [watusi/jquery-mobile-iscrollview#84]
If a page uses a popup that has a header or footer, then the height of those headers/footers is erroneously added to the total header/footer height, making the wrapper too short.

Headers/Footers in popups shouldn't be counted when calculating total fixed height.

**Comment by jtara** [comment]
Fix doesn't work for persistent headers/footers.

**Comment by mferia** [comment]
I have the problem with iphone ios 4.2.1. 
I have header and footer fixed with one panel to slide menu, but the footer not show
It seems that this is out of the screen and only see a gray box instead of footer. if I remove the panel, it works without problem.
I am using jquery mobile 1.3.1 and iscrollview  1.2.9
thank you and good widget!!
